proxies:
  - socks5://proxyes_usXvAt:XFWwtc1y@216.238.99.163:11190


accounts:
  - login:password:token


games:
  whitelist:
    - 322330

  blacklist:
    - 753


pagination_sorting:
  sort_column: 'price'
  sort_dir: 'asc'

pagination_filter:
  quantity:
    min: 0
    max: 100
  price:
    min: 10
